#![cfg_attr(not(test), no_std)]

mod acceleration;
mod angular_rate;
mod attitude;
mod battery_state;
mod command;
mod consumed_current;
mod control_mode;
mod control_system_parameters;
mod controller_demand;
mod cpu_load;
mod current;
mod drone_state;
mod erpm;
mod esc_telemetry;
mod esc_telemetry_sample;
mod imu_data;
mod motor_command;
mod motor_id;
mod pilot_command;
mod pitch_angle;
mod pitch_command;
mod radio_message;
mod remote_state;
mod roll_angle;
mod roll_command;
mod sensors;
mod telemetry_frame;
mod telemetry_frame_high_rate;
mod telemetry_frame_low_rate;
mod temperature;
mod throttle_command;
mod voltage;
mod yaw_angle;
mod yaw_command;

pub use acceleration::Acceleration;
pub use angular_rate::AngularRate;
pub use attitude::Attitude;
pub use battery_state::BatteryState;
pub use command::Command;
pub use command::FRAME_MAX_SIZE_BYTES as COMMAND_FRAME_MAX_SIZE_BYTES;
pub use consumed_current::ConsumedCurrent;
pub use control_mode::ControlMode;
pub use control_system_parameters::ControlSystemParameters;
pub use controller_demand::ControllerDemand;
pub use cpu_load::CpuLoad;
pub use current::Current;
pub use drone_state::DroneState;
pub use erpm::ERPM;
pub use esc_telemetry::ESCTelemetry;
pub use esc_telemetry_sample::ESCTelemetrySample;
pub use imu_data::ImuData;
pub use motor_command::MotorCommand;
pub use motor_id::MotorID;
pub use pilot_command::PilotCommand;
pub use pitch_angle::PitchAngle;
pub use pitch_command::PitchCommand;
pub use radio_message::DESTINATION_ADDRESS as RADIO_MESSAGE_DESTINATION_ADDRESS;
pub use radio_message::RadioMessage;
pub use remote_state::RemoteState;
pub use roll_angle::RollAngle;
pub use roll_command::RollCommand;
pub use sensors::Sensors;
pub use telemetry_frame::MAX_SIZE_BYTES as TELEMETRY_FRAME_MAX_SIZE_BYTES;
pub use telemetry_frame::TelemetryFrame;
pub use telemetry_frame_high_rate::TelemetryFrameHighRate;
pub use telemetry_frame_low_rate::TelemetryFrameLowRate;
pub use temperature::Temperature;
pub use throttle_command::ThrottleCommand;
pub use voltage::Voltage;
pub use yaw_angle::YawAngle;
pub use yaw_command::YawCommand;
